version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - fullstack-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fullstack-net

networks:
  fullstack-net: